// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-RZp78HBBjQinrK_fCBClz3EIfmu_U2g',
    appId: '1:714780267237:web:82238d60b5c69d6b0e7a0c',
    messagingSenderId: '714780267237',
    projectId: 'hansotbab-alarm',
    authDomain: 'hansotbab-alarm.firebaseapp.com',
    storageBucket: 'hansotbab-alarm.appspot.com',
    measurementId: 'G-9L5SH8TG0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUPAbc24AsZDgpa5mBhQjD1Gb83_UfdoI',
    appId: '1:714780267237:android:85c0b4ac89cfdcf50e7a0c',
    messagingSenderId: '714780267237',
    projectId: 'hansotbab-alarm',
    storageBucket: 'hansotbab-alarm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAO9C2_0SxCNvGm598Cmy2HR8iZbBBUXk',
    appId: '1:714780267237:ios:a703bc24a407de010e7a0c',
    messagingSenderId: '714780267237',
    projectId: 'hansotbab-alarm',
    storageBucket: 'hansotbab-alarm.appspot.com',
    iosBundleId: 'com.example.hansotbab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAO9C2_0SxCNvGm598Cmy2HR8iZbBBUXk',
    appId: '1:714780267237:ios:a5ce30157f5fd5aa0e7a0c',
    messagingSenderId: '714780267237',
    projectId: 'hansotbab-alarm',
    storageBucket: 'hansotbab-alarm.appspot.com',
    iosBundleId: 'com.example.hansotbab.RunnerTests',
  );
}
